# Clock signal 100 MHz

# The design utilizes board interfaces specified by the board files so its pre-constrained
# within the files generated by the block design.

# set_property -dict { PACKAGE_PIN W5   IOSTANDARD LVCMOS33 } [get_ports clk]
# create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
